# Generated by Django 5.2.6 on 2025-09-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='route',
        ),
    ]
